# It is advised to set baseURL to just "/"
baseURL = "https://example.com"
# Change this to the name of your own clinic / project if you prefer
title = "Clinic Notes"

languageCode = "en-gb"
enableEmoji = true
# Pagination is used in the calendar view. Set this to a higher number
# if you'd like to see more notes per page
paginate = 15
theme = "hugo-clinic-notes"

[taxonomies]
  patient = "patient"

[[params.menu]]
  name = "Calendar"
  url = "all/"

[[params.menu]]
  name = "Patients"
  url = "patient/"

# If you want the table of contents at the top of individual notes to index
# further levels of header (default H2) set this to a higher number
[markup]
  [markup.tableOfContents]
    endLevel = 2

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
